### ISSUE TITLE
This plugin fails to install

### ISSUE THREAD

**Issue by jsmm** [kaizau/obsidian-audio-speed-plugin#3]
Hi. I would just like to let you know that this plugin fails to install from Obsidian plugins browser.

**Comment by kaizau** [comment]
Thanks, turns out the release was linking to the wrong tag. Can you give it another try?

**Comment by jsmm** [comment]
It does install now. Thanks for sharing this plugin.

**Comment by kaizau** [comment]
Great to hear.
